# RKE2 Configuration
rke2_version: "1.32.8+rke2r1"
rke2_channel: "stable"

# Network Configuration
rke2_cluster_cidr: "10.42.0.0/16"
rke2_service_cidr: "10.43.0.0/16"
rke2_cluster_dns: "10.43.0.10"

# System Configuration
system_timezone: "Asia/Bangkok"
disable_swap: true
configure_firewall: true
enable_selinux: true

# Paths
rke2_bin_dir: "/usr/local/bin"
rke2_config_dir: "/etc/rancher/rke2"
rke2_data_dir: "/var/lib/rancher/rke2"
rke2_log_dir: "/var/log/rke2"
rke2_systemd_dir: "/etc/systemd/system"

# Token (empty = fetch from master)
rke2_token: ""

# Logging rotation
rke2_log_maxsize: "50M"
rke2_log_maxfiles: 5
