---
- name: restart rke2-server
  systemd:
    name: rke2-server
    state: restarted
    daemon_reload: yes

- name: restart rke2-agent
  systemd:
    name: rke2-agent
    state: restarted
    daemon_reload: yes

- name: save iptables
  shell: /usr/libexec/iptables/iptables.init save
  ignore_errors: yes