all:
  children:
    masters:
      hosts:
        master-01:
          ansible_host: 10.0.1.10
          rke2_type: server
    workers:
      hosts:
        worker-01:
          ansible_host: 10.0.1.20
          rke2_type: agent
        worker-02:
          ansible_host: 10.0.1.21
          rke2_type: agent