---
- name: Set timezone
  timezone:
    name: "{{ system_timezone }}"

- name: Disable swap immediately
  command: swapoff -a
  when: disable_swap

- name: Disable swap permanently
  replace:
    path: /etc/fstab
    regexp: '(^.*swap.*$)'
    replace: '# \1'
  when: disable_swap

- name: Ensure firewalld is enabled
  service:
    name: firewalld
    state: started
    enabled: yes
  when: configure_firewall

- name: Enable SELinux if requested
  selinux:
    state: enforcing
  when: enable_selinux

- name: Create RKE2 directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ rke2_bin_dir }}"
    - "{{ rke2_config_dir }}"
    - "{{ rke2_data_dir }}"
    - "{{ rke2_log_dir }}"
    - "{{ rke2_tls_cert_dir }}"

- name: Download RKE2 installation script
  get_url:
    url: https://get.rke2.io
    dest: /tmp/install-rke2.sh
    mode: 0755

- name: Install RKE2 server (master)
  shell: |
    INSTALL_RKE2_CHANNEL={{ rke2_channel }} \
    INSTALL_RKE2_TYPE=server \
    INSTALL_RKE2_VERSION={{ rke2_version }} \
    INSTALL_RKE2_BIN_DIR={{ rke2_bin_dir }} \
    INSTALL_RKE2_SYSTEMD_DIR={{ rke2_systemd_dir }} \
    /tmp/install-rke2.sh
  args:
    creates: "{{ rke2_bin_dir }}/rke2"
  when: "'master' in group_names"

- name: Install RKE2 agent (worker)
  shell: |
    INSTALL_RKE2_CHANNEL={{ rke2_channel }} \
    INSTALL_RKE2_TYPE=agent \
    INSTALL_RKE2_VERSION={{ rke2_version }} \
    INSTALL_RKE2_BIN_DIR={{ rke2_bin_dir }} \
    INSTALL_RKE2_SYSTEMD_DIR={{ rke2_systemd_dir }} \
    /tmp/install-rke2.sh
  args:
    creates: "{{ rke2_bin_dir }}/rke2"
  when: "'worker' in group_names"

- name: Fetch token from master if not defined
  fetch:
    src: /var/lib/rancher/rke2/server/node-token
    dest: /tmp/master-node-token
    flat: yes
  delegate_to: "{{ groups['master'][0] }}"
  when: rke2_token == "" and "'worker' in group_names"

- name: Set token for worker
  set_fact:
    rke2_token: "{{ lookup('file','/tmp/master-node-token') }}"
  when: rke2_token == "" and "'worker' in group_names"

- name: Deploy RKE2 config file
  template:
    src: config.yaml.j2
    dest: "{{ rke2_config_dir }}/config.yaml"
    owner: root
    group: root
    mode: 0600

# Systemd override
- name: Create systemd override directories
  file:
    path: "{{ rke2_systemd_dir }}/{{ item }}.d"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - rke2-server
    - rke2-agent

- name: Create override for master
  copy:
    dest: "{{ rke2_systemd_dir }}/rke2-server.d/override.conf"
    content: |
      [Service]
      ExecStart=
      ExecStart={{ rke2_bin_dir }}/rke2 server --config {{ rke2_config_dir }}/config.yaml --data-dir {{ rke2_data_dir }}
      StandardOutput=append:{{ rke2_log_dir }}/server.log
      StandardError=append:{{ rke2_log_dir }}/server.log
  when: "'master' in group_names"

- name: Create override for worker
  copy:
    dest: "{{ rke2_systemd_dir }}/rke2-agent.d/override.conf"
    content: |
      [Service]
      ExecStart=
      ExecStart={{ rke2_bin_dir }}/rke2 agent --config {{ rke2_config_dir }}/config.yaml --data-dir {{ rke2_data_dir }}
      StandardOutput=append:{{ rke2_log_dir }}/agent.log
      StandardError=append:{{ rke2_log_dir }}/agent.log
  when: "'worker' in group_names"

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start server
  systemd:
    name: rke2-server
    state: started
    enabled: yes
  when: "'master' in group_names"

- name: Enable and start agent
  systemd:
    name: rke2-agent
    state: started
    enabled: yes
  when: "'worker' in group_names"

- name: Wait for rke2-server active
  command: systemctl is-active rke2-server
  register: server_status
  retries: 10
  delay: 10
  until: server_status.stdout == "active"
  when: "'master' in group_names"

- name: Wait for rke2-agent active
  command: systemctl is-active rke2-agent
  register: agent_status
  retries: 10
  delay: 10
  until: agent_status.stdout == "active"
  when: "'worker' in group_names"

# Configure logrotate
- name: Create logrotate config
  copy:
    dest: /etc/logrotate.d/rke2
    content: |
      {{ rke2_log_dir }}/*.log {
          size {{ rke2_log_maxsize }}
          rotate {{ rke2_log_maxfiles }}
          compress
          copytruncate
      }
